const API_URL = "http://localhost:1337/api/questions";

const facileComplete = [
  { q: "Quelle est la capitale de la France ?", a: "Paris" },
  { q: "Combien font 2 + 2 ?", a: "4" },
  { q: "Quel animal fait 'Meuh' ?", a: "Vache" },
  { q: "Quelle est la couleur du ciel par beau temps ?", a: "Bleu" },
  { q: "Dans quel pays se trouve la Tour de Pise ?", a: "Italie" },
  { q: "Combien y a-t-il de jours dans une semaine ?", a: "7" },
  { q: "Quelle est la femelle du taureau ?", a: "Vache" },
  { q: "Quelle langue parle-t-on au Brésil ?", a: "Portugais" },
  { q: "Quel astre nous éclaire le jour ?", a: "Soleil" },
  { q: "Combien de doigts a une main humaine ?", a: "5" },
  { q: "Quel est le nom du plombier rouge de Nintendo ?", a: "Mario" },
  { q: "Comment s'appelle le petit de la poule ?", a: "Poussin" },
  { q: "Quelle est la couleur d'une émeraude ?", a: "Vert" },
  { q: "Quel langage utilise-t-on pour le style web ?", a: "CSS" },
  { q: "Quel est le plus grand chiffre sur un dé ?", a: "6" },
  { q: "Dans quel pays sont les pyramides de Gizeh ?", a: "Egypte" },
  { q: "Qui est le meilleur ami de Mickey ?", a: "Dingo" },
  { q: "Combien de minutes y a-t-il dans une heure ?", a: "60" },
  { q: "Quel est le nom de l'ogre vert au cinéma ?", a: "Shrek" },
  { q: "Quelle est la capitale du Royaume-Uni ?", a: "Londres" },
  { q: "Quel Pokémon est jaune avec des joues rouges ?", a: "Pikachu" },
  { q: "De quel pays vient la pizza ?", a: "Italie" },
  { q: "Quel animal a une très longue trompe ?", a: "Elephant" },
  { q: "Comment s'appelle l'os qui protège le cerveau ?", a: "Crane" },
  { q: "Quel est le moteur de recherche de Google ?", a: "Google" },
  { q: "Quel fruit produit le pommier ?", a: "Pomme" },
  { q: "Combien d'ailes a une abeille ?", a: "4" },
  { q: "Quelle est la capitale de l'Allemagne ?", a: "Berlin" },
  { q: "Quel est l'opposé de 'vrai' ?", a: "Faux" },
  { q: "Qui est le chevalier noir de Gotham ?", a: "Batman" },
  { q: "Quel instrument a des touches noires et blanches ?", a: "Piano" },
  { q: "Quelle saison vient après l'hiver ?", a: "Printemps" },
  { q: "Combien font 10 x 10 ?", a: "100" },
  { q: "Quel océan borde l'île de la Réunion ?", a: "Indien" },
  { q: "Quel animal est le roi de la jungle ?", a: "Lion" },
  { q: "Quel est le pays de la K-Pop ?", a: "Coree du Sud" },
  { q: "Le nom du bonhomme de neige dans La Reine des Neiges ?", a: "Olaf" },
  { q: "Quelle est la capitale des Etats-Unis ?", a: "Washington" },
  { q: "L'oiseau bleu était le logo de quel réseau ?", a: "Twitter" },
  { q: "Symbole HTML pour ouvrir une balise ?", a: "<" },
  { q: "Combien de secondes dans une minute ?", a: "60" },
  { q: "Quelle est la couleur principale du Père Noël ?", a: "Rouge" },
  { q: "Le nom de la planète où nous vivons ?", a: "Terre" },
  { q: "Qui a écrit le conte Cendrillon ?", a: "Charles Perrault" },
  { q: "Quelle est la langue la plus parlée en Chine ?", a: "Mandarin" },
  { q: "Quel sport se joue avec un ballon ovale ?", a: "Rugby" },
  { q: "Quelle est la capitale de l'Italie ?", a: "Rome" },
  { q: "Combien de côtés a un triangle ?", a: "3" },
  { q: "Quel animal est célèbre pour sa lenteur ?", a: "Paresseux" },
  { q: "Quel est le prénom du frère de Mario ?", a: "Luigi" },
  { q: "Que signifie le 'M' dans HTML ?", a: "Markup" },
  { q: "Quelle balise HTML définit le titre principal ?", a: "h1" },
  { q: "Quel symbole CSS cible une classe ?", a: "." },
  { q: "Quel langage crée la structure d'un site ?", a: "HTML" },
  { q: "Quel animal est le logo de GitHub ?", a: "Octocat" },
  { q: "Comment appelle-t-on une erreur de code ?", a: "Bug" },
  { q: "Quelle touche efface le caractère précédent ?", a: "Backspace" },
  { q: "Quel navigateur a été créé par Google ?", a: "Chrome" },
  { q: "Que signifie l'extension .js ?", a: "JavaScript" },
  { q: "Quelle touche clavier permet d'aller à la ligne ?", a: "Entree" },
  { q: "Quel est le nom de la souris de l'ordinateur ?", a: "Souris" },
  { q: "Comment s'appelle l'écran de l'ordinateur ?", a: "Moniteur" },
  { q: "Quel symbole ferme une balise HTML ?", a: "/" },
  { q: "Quel langage utilise-t-on pour les bases de données ?", a: "SQL" },
  { q: "Quelle est la touche pour copier (Windows) ?", a: "Ctrl+C" },
  { q: "Quelle est la touche pour coller (Windows) ?", a: "Ctrl+V" },
  { q: "Quel est le réseau social pour les professionnels ?", a: "LinkedIn" },
  { q: "Quel est le nom du système d'Apple pour iPhone ?", a: "iOS" },
  { q: "Quel est le système d'exploitation libre ?", a: "Linux" },
  { q: "Quelle unité mesure la taille d'un fichier ?", a: "Octet" },
  { q: "Quelle est la console de Nintendo qui se 'switch' ?", a: "Switch" },
  { q: "Comment s'appelle l'héroïne de Tomb Raider ?", a: "Lara Croft" },
  { q: "Dans quel jeu construit-on avec des cubes ?", a: "Minecraft" },
  { q: "Quel est le nom du hérisson bleu de Sega ?", a: "Sonic" },
  { q: "Dans quel jeu mange-t-on des pac-gommes ?", a: "Pac-Man" },
  { q: "Quelle est la couleur de la casquette de Mario ?", a: "Rouge" },
  { q: "Comment s'appelle le héros de Zelda ?", a: "Link" },
  { q: "Quel jeu de guerre a pour mode 'Battle Royale' ?", a: "Fortnite" },
  { q: "Quelle entreprise fabrique la Xbox ?", a: "Microsoft" },
  { q: "Comment s'appelle le petit dinosaure vert ami de Mario ?", a: "Yoshi" },
  { q: "Quelle est la couleur de la casquette de Luigi ?", a: "Vert" },
  { q: "Dans quel jeu capture-t-on des monstres dans des balles ?", a: "Pokemon" },
  { q: "Quel est le nom de la princesse dans Zelda ?", a: "Zelda" },
  { q: "Quel jeu consiste à empiler des briques russes ?", a: "Tetris" },
  { q: "Comment s'appelle la console de Sony ?", a: "PlayStation" },
  { q: "Quelle est la couleur d'une carotte ?", a: "Orange" },
  { q: "Quel est le jour après lundi ?", a: "Mardi" },
  { q: "Quelle saison vient après l'automne ?", a: "Hiver" },
  { q: "Quel est le premier mois de l'année ?", a: "Janvier" },
  { q: "Quel est le pays de la Tour Eiffel ?", a: "France" },
  { q: "Quelle est la couleur d'une banane ?", a: "Jaune" },
  { q: "Quel est l'animal qui fait 'Wouf' ?", a: "Chien" },
  { q: "Quelle est la couleur du lait ?", a: "Blanc" },
  { q: "Quel organe sert à entendre ?", a: "Oreille" },
  { q: "Quel est le nom de la planète rouge ?", a: "Mars" },
  { q: "Quel insecte fabrique du miel ?", a: "Abeille" },
  { q: "Combien font 5 + 5 ?", a: "10" },
  { q: "Quel est l'opposé de 'froid' ?", a: "Chaud" },
  { q: "Quelle est la capitale du Portugal ?", a: "Lisbonne" },
  { q: "Quel fruit est utilisé pour faire du vin ?", a: "Raisin" },
  { q: "Comment s'appelle le petit du chien ?", a: "Chiot" },
  { q: "Quelle est la couleur des feuilles en été ?", a: "Vert" },
  { q: "Quel pays a pour capitale Madrid ?", a: "Espagne" },
  { q: "Quelle est la capitale de la Belgique ?", a: "Bruxelles" },
  { q: "Quel astre nous éclaire la nuit ?", a: "Lune" },
  { q: "Combien d'heures y a-t-il dans une journée ?", a: "24" },
  { q: "Quel vêtement porte-t-on sur les mains en hiver ?", a: "Gants" },
  { q: "Quel est le nom du bébé du chat ?", a: "Chaton" },
  { q: "De quelle couleur est le chocolat ?", a: "Marron" },
  { q: "Quel instrument de musique a 6 cordes ?", a: "Guitare" },
  { q: "Quelle est la capitale du Japon ?", a: "Tokyo" },
  { q: "Quel animal a un très long cou ?", a: "Girafe" },
  { q: "Quel pays a pour capitale Rome ?", a: "Italie" },
  { q: "Combien de pattes a une araignée ?", a: "8" },
  { q: "Quel est l'animal qui miaule ?", a: "Chat" },
  { q: "Quel est le nom du repas du matin ?", a: "Petit-dejeuner" },
  { q: "Quelle est la couleur d'une fraise ?", a: "Rouge" },
  { q: "Quel objet sert à se protéger de la pluie ?", a: "Parapluie" },
  { q: "Quelle est la monnaie de la France ?", a: "Euro" },
  { q: "Quel pays a pour capitale Moscou ?", a: "Russie" },
  { q: "Comment s'appelle le mâle de la vache ?", a: "Taureau" },
  { q: "Quel est l'animal qui produit des œufs ?", a: "Poule" },
  { q: "Quel est le plus grand océan du monde ?", a: "Pacifique" },
  { q: "Quelle est la capitale de l'Espagne ?", a: "Madrid" },
  { q: "Quel fruit est jaune et acide ?", a: "Citron" },
  { q: "Quel outil sert à boire de la soupe ?", a: "Cuillere" },
  { q: "Comment s'appelle le petit de la jument ?", a: "Poulain" },
  { q: "Quel pays a pour capitale Ottawa ?", a: "Canada" },
  { q: "Quel est l'animal le plus rapide du monde ?", a: "Guepard" },
  { q: "Quelle est la couleur d'une écorce d'arbre ?", a: "Marron" },
  { q: "Quel est le nom de notre galaxie ?", a: "Voie Lactee" },
  { q: "Combien de côtés a un carré ?", a: "4" },
  { q: "Quelle langue parle-t-on au Mexique ?", a: "Espagnol" },
  { q: "Quel est le nom de la fée dans Peter Pan ?", a: "Clochette" },
  { q: "Quel animal change de couleur ?", a: "Cameleon" },
  { q: "Quel est le fruit préféré des singes ?", a: "Banane" },
  { q: "Quelle est la capitale de la Chine ?", a: "Pekin" },
  { q: "Comment s'appelle le petit du mouton ?", a: "Agneau" },
  { q: "Quel vêtement porte-t-on sur la tête ?", a: "Chapeau" },
  { q: "Quel est le cri du lion ?", a: "Rugissement" },
  { q: "Quelle est la capitale de l'Egypte ?", a: "Le Caire" },
  { q: "Quel est le plus haut sommet du monde ?", a: "Everest" },
  { q: "Quel animal est connu pour sa bosse ?", a: "Chameau" },
  { q: "Quelle est la capitale de la Grèce ?", a: "Athenes" },
  { q: "Quel oiseau ne peut pas voler ?", a: "Autruche" },
  { q: "Quel est le nom du navire qui a coulé en 1912 ?", a: "Titanic" },
  { q: "Comment s'appelle le bébé du lapin ?", a: "Lapereau" },
  { q: "Quelle est la couleur d'une cerise ?", a: "Rouge" },
  { q: "Combien de secondes y a-t-il dans une minute ?", a: "60" },
  { q: "Quel pays a pour capitale Canberra ?", a: "Australie" }
];

const moyenComplete = [
  { q: "Quel est le plus grand océan du monde ?", a: "Pacifique" },
  { q: "Qui a peint la Joconde ?", a: "Leonard de Vinci" },
  { q: "Combien de planètes compte le système solaire ?", a: "8" },
  { q: "Pays vainqueur de la Coupe du Monde 2018 ?", a: "France" },
  { q: "Quelle est la capitale de l'Espagne ?", a: "Madrid" },
  { q: "Quel est l'organe qui pompe le sang ?", a: "Coeur" },
  { q: "En quelle année est tombé le mur de Berlin ?", a: "1989" },
  { q: "Quel métal est liquide à température ambiante ?", a: "Mercure" },
  { q: "Quel est le plus grand mammifère terrestre ?", a: "Elephant" },
  { q: "Qui a écrit 'Le Petit Prince' ?", a: "Saint-Exupery" },
  { q: "Quel studio a créé Star Wars ?", a: "Lucasfilm" },
  { q: "Le langage de script standard pour le web ?", a: "JavaScript" },
  { q: "Quel chanteur est le 'King of Pop' ?", a: "Michael Jackson" },
  { q: "Dans quel jeu trouve-t-on Master Chief ?", a: "Halo" },
  { q: "Quelle est la monnaie du Japon ?", a: "Yen" },
  { q: "Quel élément chimique a pour symbole 'H' ?", a: "Hydrogene" },
  { q: "Quel pays a offert la Statue de la Liberté ?", a: "France" },
  { q: "Ville surnommée 'La Grosse Pomme' ?", a: "New York" },
  { q: "Qui a fondé Facebook ?", a: "Mark Zuckerberg" },
  { q: "Quel est le plus long fleuve d'Europe ?", a: "Volga" },
  { q: "Quel est le nom de l'IA dans Portal ?", a: "GLaDOS" },
  { q: "Dans quel groupe chantait Freddie Mercury ?", a: "Queen" },
  { q: "Format d'image web gérant la transparence ?", a: "PNG" },
  { q: "Quelle est la capitale de la Russie ?", a: "Moscou" },
  { q: "Réalisateur du film 'Inception' ?", a: "Christopher Nolan" },
  { q: "Framework PHP célèbre commençant par L ?", a: "Laravel" },
  { q: "Le cerveau d'un ordinateur (sigle) ?", a: "CPU" },
  { q: "Quelle est la capitale de la Turquie ?", a: "Ankara" },
  { q: "Quel est le cri du hibou ?", a: "Hululement" },
  { q: "Jeu vidéo de briques créé par Pajitnov ?", a: "Tetris" },
  { q: "Qui a écrit Harry Potter ?", a: "J.K. Rowling" },
  { q: "Le plus grand désert froid du monde ?", a: "Antarctique" },
  { q: "Quel pays est désormais le plus peuplé ?", a: "Inde" },
  { q: "Qui a fondé la société SpaceX ?", a: "Elon Musk" },
  { q: "Gaz absorbé par les plantes et rejeté par l'homme ?", a: "CO2" },
  { q: "Pays surnommé 'l'Empire du Milieu' ?", a: "Chine" },
  { q: "Qui a découvert la loi de la gravitation ?", a: "Isaac Newton" },
  { q: "Le nom de code de l'agent 007 ?", a: "James Bond" },
  { q: "Langage pour requêter une base de données ?", a: "SQL" },
  { q: "Quelle est la capitale du Canada ?", a: "Ottawa" },
  { q: "L'animal terrestre le plus rapide ?", a: "Guepard" },
  { q: "Co-fondateur d'Apple avec Steve Jobs ?", a: "Steve Wozniak" },
  { q: "Quelle ville a accueilli les JO d'été 2024 ?", a: "Paris" },
  { q: "Prénom de la compagne de Spider-Man ?", a: "Mary Jane" },
  { q: "Pays ayant pour capitale Lisbonne ?", a: "Portugal" },
  { q: "Fleur symbole des Pays-Bas ?", a: "Tulipe" },
  { q: "Un des trois protagonistes de GTA V ?", a: "Franklin" },
  { q: "Interprète de la chanson 'Blinding Lights' ?", a: "The Weeknd" },
  { q: "La planète surnommée 'la planète rouge' ?", a: "Mars" },
  { q: "Balise HTML pour une liste à puces ?", a: "ul" },
  { q: "Que signifie CSS ?", a: "Cascading Style Sheets" },
  { q: "Quelle méthode JS ajoute un élément à la fin d'un tableau ?", a: "push" },
  { q: "Quel est le port par défaut du protocole HTTP ?", a: "80" },
  { q: "Quel framework JS a été créé par Facebook ?", a: "React" },
  { q: "En CSS, quelle propriété gère l'épaisseur de la police ?", a: "font-weight" },
  { q: "Que signifie l'acronyme URL ?", a: "Uniform Resource Locator" },
  { q: "Quel outil utilise-t-on pour versionner son code ?", a: "Git" },
  { q: "Comment appelle-t-on la partie serveur d'un site ?", a: "Backend" },
  { q: "En JS, quel mot-clé déclare une variable qui peut changer ?", a: "let" },
  { q: "Quelle propriété CSS définit la couleur de fond ?", a: "background-color" },
  { q: "Quel est le format d'échange de données léger du Web ?", a: "JSON" },
  { q: "Que signifie API ?", a: "Application Programming Interface" },
  { q: "Quel symbole utilise-t-on pour une classe en CSS ?", a: "." },
  { q: "En SQL, quel mot-clé permet de supprimer des données ?", a: "DELETE" },
  { q: "Quel protocole est la version sécurisée de HTTP ?", a: "HTTPS" },
  { q: "Quel outil permet de gérer les paquets en Node.js ?", a: "npm" },
  { q: "Quelle unité CSS est relative à la taille de la police parente ?", a: "em" },
  { q: "Quelle balise HTML est utilisée pour un saut de ligne ?", a: "br" },
  { q: "Comment appelle-t-on un site qui s'adapte aux mobiles ?", a: "Responsive" },
  { q: "Quelle méthode JS transforme une chaîne en minuscule ?", a: "toLowerCase" },
  { q: "Quel studio a développé le jeu 'The Witcher' ?", a: "CD Projekt Red" },
  { q: "Dans quel jeu affronte-t-on des 'Creepers' ?", a: "Minecraft" },
  { q: "Quelle est l'héroïne de la série 'Metroid' ?", a: "Samus Aran" },
  { q: "Dans quel jeu cherche-t-on la 'Triforce' ?", a: "Zelda" },
  { q: "Comment s'appelle l'IA de Tony Stark dans Iron Man ?", a: "JARVIS" },
  { q: "Quel est le nom du monde de 'The Legend of Zelda' ?", a: "Hyrule" },
  { q: "Dans 'League of Legends', quel est le nom de la carte ?", a: "Faille de l'invocateur" },
  { q: "Quel personnage est surnommé 'Le Loup Blanc' ?", a: "Geralt de Riv" },
  { q: "Qui est le créateur du jeu Metal Gear ?", a: "Hideo Kojima" },
  { q: "Quel est le jeu de combat phare de Capcom ?", a: "Street Fighter" },
  { q: "Quelle couleur est la pilule du réveil dans Matrix ?", a: "Rouge" },
  { q: "Dans Pokémon, quelle pierre fait évoluer Pikachu ?", a: "Pierre Foudre" },
  { q: "Comment s'appelle le vaisseau de Han Solo ?", a: "Faucon Millenium" },
  { q: "Quel studio a créé 'The Last of Us' ?", a: "Naughty Dog" },
  { q: "Dans quel jeu tire-t-on sur des portails oranges et bleus ?", a: "Portal" },
  { q: "Quelle est la capitale de l'Australie ?", a: "Canberra" },
  { q: "Qui a écrit 'Les Misérables' ?", a: "Victor Hugo" },
  { q: "Quelle est la capitale du Portugal ?", a: "Lisbonne" },
  { q: "Quel explorateur a découvert l'Amérique en 1492 ?", a: "Christophe Colomb" },
  { q: "Quelle est la capitale de la Grèce ?", a: "Athenes" },
  { q: "Qui a peint 'Le Cri' ?", a: "Edvard Munch" },
  { q: "Quel est le plus grand désert chaud du monde ?", a: "Sahara" },
  { q: "Quelle est la capitale de la Suède ?", a: "Stockholm" },
  { q: "En quelle année a débuté la Première Guerre mondiale ?", a: "1914" },
  { q: "Quel fleuve traverse l'Égypte ?", a: "Nil" },
  { q: "Quelle est la capitale de la Belgique ?", a: "Bruxelles" },
  { q: "Qui a sculpté 'Le Penseur' ?", a: "Rodin" },
  { q: "Quelle est la capitale de l'Irlande ?", a: "Dublin" },
  { q: "Qui était le roi de France surnommé le Roi-Soleil ?", a: "Louis XIV" },
  { q: "Quel pays possède le plus de fuseaux horaires ?", a: "France" },
  { q: "Quelle est la capitale du Mexique ?", a: "Mexico" },
  { q: "Quelle mer sépare l'Europe de l'Afrique ?", a: "Mediterranee" },
  { q: "Qui a écrit 'Le Bourgeois gentilhomme' ?", a: "Moliere" },
  { q: "Quelle est la capitale du Vietnam ?", a: "Hanoi" },
  { q: "Quelle est la monnaie de la Grande-Bretagne ?", a: "Livre Sterling" },
  { q: "Quel est le nom du robot dans Wall-E ?", a: "Wall-E" },
  { q: "Quelle est la capitale de la Norvège ?", a: "Oslo" },
  { q: "En quelle année est tombé le Premier Empire ?", a: "1815" },
  { q: "Quelle est la capitale de la Suisse ?", a: "Berne" },
  { q: "Qui a découvert la radioactivité ?", a: "Marie Curie" },
  { q: "Quel pays a pour capitale Buenos Aires ?", a: "Argentine" },
  { q: "Quel fleuve traverse Londres ?", a: "Tamise" },
  { q: "Qui est l'auteur de 'Roméo et Juliette' ?", a: "Shakespeare" },
  { q: "Quelle est la capitale de la Corée du Sud ?", a: "Seoul" },
  { q: "Quel organe est responsable de l'équilibre ?", a: "Oreille interne" },
  { q: "Qui a inventé le vaccin contre la rage ?", a: "Louis Pasteur" },
  { q: "Quelle est la capitale de la Turquie ?", a: "Ankara" },
  { q: "Quel pays est surnommé le 'Pays du Matin Calme' ?", a: "Coree du Sud" },
  { q: "Qui a écrit 'L'Étranger' ?", a: "Albert Camus" },
  { q: "Quelle est la capitale de l'Autriche ?", a: "Vienne" },
  { q: "Quel est le plus grand pays du monde par sa surface ?", a: "Russie" },
  { q: "Qui a peint 'Les Nymphéas' ?", a: "Claude Monet" },
  { q: "Quelle est la capitale de la Thaïlande ?", a: "Bangkok" },
  { q: "En quel siècle s'est déroulée la Renaissance ?", a: "16eme" },
  { q: "Quelle est la capitale de la Pologne ?", a: "Varsovie" },
  { q: "Quel gaz absorbe les UV dans l'atmosphère ?", a: "Ozone" },
  { q: "Quelle est la capitale de la Croatie ?", a: "Zagreb" },
  { q: "Qui a écrit 'L'Odyssée' ?", a: "Homere" },
  { q: "Quel est le nom du pigment vert des plantes ?", a: "Chlorophylle" },
  { q: "Quelle est la capitale de la Roumanie ?", a: "Bucarest" },
  { q: "Quel physicien a formulé E=mc2 ?", a: "Einstein" },
  { q: "Quelle est la capitale de l'Islande ?", a: "Reykjavik" },
  { q: "Qui a écrit 'Don Quichotte' ?", a: "Cervantes" },
  { q: "Quel pays a pour capitale New Delhi ?", a: "Inde" },
  { q: "Quelle est la capitale de la Colombie ?", a: "Bogota" },
  { q: "Quel pays a pour capitale Rabat ?", a: "Maroc" },
  { q: "Quelle est la capitale de la Finlande ?", a: "Helsinki" },
  { q: "Qui a peint 'La Naissance de Vénus' ?", a: "Botticelli" },
  { q: "Quelle est la capitale de la Hongrie ?", a: "Budapest" },
  { q: "Quel pays a pour capitale Nairobi ?", a: "Kenya" },
  { q: "Quelle est la capitale de l'Arabie Saoudite ?", a: "Riyad" },
  { q: "Qui est le dieu de la guerre dans la mythologie grecque ?", a: "Ares" },
  { q: "Quelle est la capitale de la Nouvelle-Zélande ?", a: "Wellington" },
  { q: "Quel animal est le symbole de l'Australie ?", a: "Kangourou" },
  { q: "Quelle est la capitale de Cuba ?", a: "La Havane" },
  { q: "Qui a composé 'La Flûte enchantée' ?", a: "Mozart" },
  { q: "Quelle est la capitale du Chili ?", a: "Santiago" },
  { q: "Quel oiseau est capable de voler en arrière ?", a: "Colibri" },
  { q: "Quelle est la capitale de la Malaisie ?", a: "Kuala Lumpur" },
  { q: "Qui a écrit 'Germinal' ?", a: "Emile Zola" }
];

const difficileComplete = [
  { q: "Quel est le symbole chimique de l'or ?", a: "Au" },
  { q: "Année du premier pas de l'homme sur la lune ?", a: "1969" },
  { q: "Combien de coeurs possède une pieuvre ?", a: "3" },
  { q: "Quelle est la capitale de l'Australia ?", a: "Canberra" },
  { q: "Le plus long fleuve du monde ?", a: "Amazone" },
  { q: "Qui a découvert la pénicilline ?", a: "Fleming" },
  { q: "Élément le plus abondant dans l'univers ?", a: "Hydrogene" },
  { q: "Où se trouve le siège principal de l'ONU ?", a: "New York" },
  { q: "Le nom de notre galaxie ?", a: "Voie Lactee" },
  { q: "Qui a peint le tableau 'Guernica' ?", a: "Picasso" },
  { q: "Philosophe auteur de 'Ainsi parlait Zarathoustra' ?", a: "Nietzsche" },
  { q: "Vitesse de la lumière (en milliers de km/s) ?", a: "300" },
  { q: "Le nom de l'IA accompagnant Major-General dans Halo ?", a: "Cortana" },
  { q: "Année de création du noyau Linux ?", a: "1991" },
  { q: "Compositeur de 'La Flute enchantee' ?", a: "Mozart" },
  { q: "La première femme programmeuse ?", a: "Ada Lovelace" },
  { q: "Protagoniste principal de Metal Gear Solid ?", a: "Solid Snake" },
  { q: "Protocole de transfert de fichiers (sigle) ?", a: "FTP" },
  { q: "Compositeur de la 9ème symphonie (Ode à la joie) ?", a: "Beethoven" },
  { q: "Créateur du langage de programmation C ?", a: "Dennis Ritchie" },
  { q: "Jeu 'Battle Royale' ayant lancé la mode en 2017 ?", a: "PUBG" },
  { q: "Quelle est la capitale de l'Islande ?", a: "Reykjavik" },
  { q: "Le plus petit pays du monde ?", a: "Vatican" },
  { q: "Auteur du roman complexe 'Ulysse' ?", a: "James Joyce" },
  { q: "Particule de charge négative dans l'atome ?", a: "Electron" },
  { q: "Nom de l'algorithme de classement initial de Google ?", a: "PageRank" },
  { q: "Capitale actuelle du Kazakhstan ?", a: "Astana" },
  { q: "Inventeur du World Wide Web (nom complet) ?", a: "Tim Berners-Lee" },
  { q: "Pays abritant le temple d'Angkor Wat ?", a: "Cambodge" },
  { q: "Quelle est la monnaie de la Suisse ?", a: "Franc Suisse" },
  { q: "IA sarcastique dans le film Interstellar ?", a: "TARS" },
  { q: "Mathématicien ayant cassé le code Enigma ?", a: "Alan Turing" },
  { q: "Élément chimique au numéro atomique 1 ?", a: "Hydrogene" },
  { q: "Capitale de la Corée du Nord ?", a: "Pyongyang" },
  { q: "Auteur des aventures de Sherlock Holmes ?", a: "Arthur Conan Doyle" },
  { q: "Inventeur de la première pile électrique ?", a: "Alessandro Volta" },
  { q: "Premier satellite artificiel mis en orbite ?", a: "Spoutnik" },
  { q: "Opéra de Bizet se déroulant à Séville ?", a: "Carmen" },
  { q: "Plus haut sommet du continent africain ?", a: "Kilimandjaro" },
  { q: "Créateur du langage Python ?", a: "Guido van Rossum" },
  { q: "Quelle est la capitale du Vietnam ?", a: "Hanoi" },
  { q: "Siècle de la Renaissance italienne (chiffre) ?", a: "15" },
  { q: "Pays possédant le plus grand nombre d'îles ?", a: "Suede" },
  { q: "Peintre expressionniste auteur du 'Cri' ?", a: "Edvard Munch" },
  { q: "Quelle est la capitale du Nigeria ?", a: "Abuja" },
  { q: "Processeur spécialisé dans le calcul graphique ?", a: "GPU" },
  { q: "Auteur du roman dystopique '1984' ?", a: "George Orwell" },
  { q: "Le plus grand lac d'Afrique ?", a: "Victoria" },
  { q: "Année de naissance du langage JavaScript ?", a: "1995" },
  { q: "Nom de l'IA créée par Tony Stark ?", a: "JARVIS" },
  { q: "En JS, comment appelle-t-on la remontée des déclarations ?", a: "Hoisting" },
  { q: "Quel code HTTP correspond à une erreur serveur interne ?", a: "500" },
  { q: "Quel est le moteur JavaScript de Google Chrome ?", a: "V8" },
  { q: "Que signifie le 'A' dans l'architecture CPU ARM ?", a: "Advanced" },
  { q: "En CSS, quelle est la spécificité d'une ID par rapport à une classe ?", a: "Plus elevee" },
  { q: "Quel protocole est utilisé pour envoyer des emails ?", a: "SMTP" },
  { q: "En JS, quelle fonction permet d'attendre une Promise ?", a: "await" },
  { q: "Comment appelle-t-on une fonction qui s'appelle elle-même ?", a: "Recursive" },
  { q: "Quel est le nom de la première interface graphique (Xerox) ?", a: "Alto" },
  { q: "En SQL, quel mot-clé combine les résultats de deux SELECT ?", a: "UNION" },
  { q: "Quel algorithme de compression est utilisé pour les fichiers ZIP ?", a: "DEFLATE" },
  { q: "Quelle méthode HTTP est utilisée pour mettre à jour partiellement une ressource ?", a: "PATCH" },
  { q: "Comment appelle-t-on le fait d'isoler une fonction de son contexte ?", a: "Closure" },
  { q: "Quel est le nom du langage de bas niveau juste au-dessus du binaire ?", a: "Assembleur" },
  { q: "En React, quel Hook gère les effets de bord ?", a: "useEffect" },
  { q: "Quelle est la complexité temporelle d'une recherche binaire ?", a: "O(log n)" },
  { q: "Quel protocole réseau fonctionne sur la couche 4 (Transport) ?", a: "TCP" },
  { q: "Quel est le nom du créateur de la base de données MySQL ?", a: "Michael Widenius" },
  { q: "En JS, que renvoie 'typeof null' ?", a: "object" },
  { q: "Quel format de fichier est utilisé pour les certificats SSL ?", a: "PEM" },
  { q: "Dans 'BioShock', comment s'appelle la ville sous-marine ?", a: "Rapture" },
  { q: "Quel est le nom du moteur de jeu de 'Half-Life 2' ?", a: "Source" },
  { q: "En quelle année est sortie la première PlayStation au Japon ?", a: "1994" },
  { q: "Qui est le compositeur de la musique de 'Final Fantasy' ?", a: "Nobuo Uematsu" },
  { q: "Quel jeu a introduit le premier 'Easter Egg' de l'histoire ?", a: "Adventure" },
  { q: "Comment s'appelle l'antagoniste principal de 'Final Fantasy VII' ?", a: "Sephiroth" },
  { q: "Dans 'Dark Souls', quel est le nom du pays dévasté ?", a: "Lordran" },
  { q: "Quel studio a créé le jeu 'Cuphead' ?", a: "Studio MDHR" },
  { q: "Quelle console de Sega a été la dernière produite ?", a: "Dreamcast" },
  { q: "Dans 'Mass Effect', quel est le nom de la race des moissonneurs ?", a: "Reapers" },
  { q: "Quel est l'élément chimique au symbole 'W' ?", a: "Tungstene" },
  { q: "Quelle est la capitale de la Mongolie ?", a: "Oulan-Bator" },
  { q: "Qui a formulé la théorie de la relativité générale ?", a: "Einstein" },
  { q: "Quel est l'os le plus petit du corps humain ?", a: "Etrier" },
  { q: "Dans quel pays se trouve le désert d'Atacama ?", a: "Chili" },
  { q: "Qui a écrit 'La Condition humaine' ?", a: "Andre Malraux" },
  { q: "Quel est le nom de la particule élémentaire de la lumière ?", a: "Photon" },
  { q: "Quelle est la capitale du Sri Lanka ?", a: "Sri Jayawardenepura Kotte" },
  { q: "Qui a peint 'Les Menines' ?", a: "Velasquez" },
  { q: "En quelle année a été signé le traité de Versailles ?", a: "1919" },
  { q: "Quel est le plus grand satellite de Saturne ?", a: "Titan" },
  { q: "Quel philosophe a dit 'Je pense, donc je suis' ?", a: "Descartes" },
  { q: "Quel pays possède la plus grande réserve de pétrole ?", a: "Venezuela" },
  { q: "Quel est le nom du détroit entre la Russie et l'Alaska ?", a: "Bering" },
  { q: "Quelle est la capitale de l'Arménie ?", a: "Erevan" },
  { q: "Qui a composé 'Le Lac des cygnes' ?", a: "Tchaikovski" },
  { q: "Quelle est la distance moyenne Terre-Soleil (UA) ?", a: "1" },
  { q: "Quel est le métal le plus cher du monde ?", a: "Rhodium" },
  { q: "Qui a écrit 'Le Crépuscule des Idoles' ?", a: "Nietzsche" },
  { q: "Quelle est la capitale de l'Équateur ?", a: "Quito" },
  { q: "Quel oiseau est le symbole de la Nouvelle-Zélande ?", a: "Kiwi" },
  { q: "Dans quelle ville se trouve le musée de l'Ermitage ?", a: "Saint-Petersbourg" },
  { q: "Quel est le symbole chimique de l'Antimoine ?", a: "Sb" },
  { q: "Quelle est la langue officielle du Suriname ?", a: "Neerlandais" },
  { q: "Qui a peint 'La Jeune Fille à la perle' ?", a: "Vermeer" },
  { q: "Quel est le nom du nuage de comètes aux confins du système solaire ?", a: "Nuage d'Oort" },
  { q: "Quelle est la capitale de la Lettonie ?", a: "Riga" },
  { q: "Qui a écrit 'Faust' ?", a: "Goethe" },
  { q: "Quel est le plus grand pays d'Afrique par superficie ?", a: "Algerie" },
  { q: "Quel est le nom de la fosse la plus profonde de l'océan ?", a: "Mariannes" },
  { q: "Quelle est la capitale de la Jordanie ?", a: "Amman" },
  { q: "Quel gaz noble a le numéro atomique 54 ?", a: "Xenon" },
  { q: "Qui a sculpté le 'David' en marbre ?", a: "Michel-Ange" },
  { q: "Quelle est la capitale de la Géorgie ?", a: "Tbilissi" },
  { q: "Quel est le nom de l'échelle mesurant l'alcanité ?", a: "pH" },
  { q: "Qui a écrit 'Guerre et Paix' ?", a: "Tolstoi" },
  { q: "Quelle est la capitale de l'Ouzbékistan ?", a: "Tachkent" },
  { q: "Quel est l'élément chimique au symbole 'Sn' ?", a: "Etain" },
  { q: "Quelle est la monnaie de la Corée du Sud ?", a: "Won" },
  { q: "Quelle est la capitale du Népal ?", a: "Katmandou" },
  { q: "Qui a écrit 'Le Prince' ?", a: "Machiavel" },
  { q: "Quel est l'élément le plus dense de la Terre ?", a: "Osmium" },
  { q: "Quelle est la capitale du Bhoutan ?", a: "Thimphu" },
  { q: "Qui a peint 'L'École d'Athènes' ?", a: "Raphael" },
  { q: "Quel est le nom du volcan qui a détruit Pompéi ?", a: "Vesuve" },
  { q: "Quelle est la capitale du Panama ?", a: "Panama City" },
  { q: "Quel est le nom de l'inventeur de la dynamite ?", a: "Alfred Nobel" },
  { q: "Quelle est la capitale de la Bolivie (administrative) ?", a: "La Paz" },
  { q: "Qui a écrit 'Les Fleurs du Mal' ?", a: "Baudelaire" },
  { q: "Quelle est la capitale de l'Estonie ?", a: "Tallinn" },
  { q: "Quel est le symbole chimique du Plomb ?", a: "Pb" },
  { q: "Quel est le nom de la mer entre le Japon et la Corée ?", a: "Mer du Japon" },
  { q: "Quelle est la capitale du Kenya ?", a: "Nairobi" },
  { q: "Qui a composé les 'Nocturnes' ?", a: "Chopin" },
  { q: "Quelle est la capitale de la Libye ?", a: "Tripoli" },
  { q: "Quel pays a pour capitale Addis-Abeba ?", a: "Ethiopie" },
  { q: "Quel est le nom de la couche la plus haute de l'atmosphère ?", a: "Exosphere" },
  { q: "Quelle est la capitale du Paraguay ?", a: "Asuncion" },
  { q: "Qui a écrit 'L'Être et le Néant' ?", a: "Sartre" },
  { q: "Quel est le symbole chimique du Potassium ?", a: "K" },
  { q: "Quelle est la capitale du Laos ?", a: "Vientiane" },
  { q: "Qui a peint 'Le Déjeuner sur l'herbe' ?", a: "Manet" },
  { q: "Quelle est la capitale de la Moldavie ?", a: "Chisinau" },
  { q: "Quel est le nom du satellite naturel de Mars ?", a: "Phobos" },
  { q: "Quelle est la capitale du Mali ?", a: "Bamako" },
  { q: "Qui a écrit 'Cent ans de solitude' ?", a: "Gabriel Garcia Marquez" },
  { q: "Quel est le symbole chimique de l'Argent ?", a: "Ag" },
  { q: "Quelle est la capitale du Myanmar ?", a: "Naypyidaw" },
  { q: "Qui a composé 'Symphonie fantastique' ?", a: "Berlioz" },
  { q: "Quelle est la capitale du Honduras ?", a: "Tegucigalpa" }
];

const questionsData = {
  facile: facileComplete,
  moyen: moyenComplete,
  difficile: difficileComplete
};

async function seed() {
  console.log("🚀 Nettoyage de sécurité avant import...");
  console.log("🚀 Début de l'importation...");
  
  for (const [niveau, liste] of Object.entries(questionsData)) {
    for (const item of liste) {
      try {
        const response = await fetch(API_URL, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            data: {
              intitule: item.q,
              reponse: item.a,
              niveau: niveau,
              publishedAt: new Date()
            }
          })
        });
        
        if (response.ok) {
          console.log(`✅ ${niveau}: ${item.q.substring(0, 20)}...`);
        } else {
          console.error(`❌ Erreur Strapi: ${response.statusText}`);
        }
      } catch (error) {
        console.error("❌ Erreur de connexion:", error);
      }
    }
  }
  console.log("🏁 Importation terminée avec succès !");
}

seed();